<h1>Caso de uso: Canciones de Spotify<h1>

A continuaciónse obtendrá la información de un archivo JSON que contine un total de 45.128 canciones de spotify, cada una de ellas con la siguiente información
- *track*: nombre de la canción
- *album*: nombre del album al que pertenece
- *artist*: nombre del artista
- *duration*: duración en milisegundos
- *genres*: lista de generos del artista

In [3]:
import pandas as pd

In [6]:
df_canciones = pd.read_json(r'..\Troncal\T1-herramientas_programación\ejercicios\data\tracks.json')

In [9]:
df_canciones.head()

,track,album,artist,duration,genres
0,"Andante, Andante",Super Trouper,ABBA,278880,"[europop, swedish pop]"
1,As Good As New - Live,Live At Wembley Arena,ABBA,206080,"[europop, swedish pop]"
2,Bang-A-Boomerang,Abba,ABBA,185109,"[europop, swedish pop]"
3,Cassandra,The Visitors,ABBA,296705,"[europop, swedish pop]"
4,Chiquitita,Voulez-Vous,ABBA,328000,"[europop, swedish pop]"

<h3>Pregunta<h3>
<h4>
1. ¿Qué duración tiene la canción `The Show Must Go On - Remastered 2011` del grupo `Queen`? <h4>

In [16]:
df_canciones[(df_canciones.artist=="Queen") & (df_canciones.track=="The Show Must Go On - Remastered 2011")]

,track,album,artist,duration,genres
33336,The Show Must Go On - Remastered 2011,Innuendo (2011 Remaster),Queen,277827,"[album rock, classic rock, glam rock, heavy ch..."

<h4>2. ¿Cuántas canciones diferentes a remasterizado Queen? Es decir, ¿Cuántas de sus canciones contienen el texto Remastered?

In [21]:
df_canciones[(df_canciones.artist=="Queen") & (df_canciones.track.str.contains("Remastered"))].track.count()

np.int64(91)

In [22]:
df_canciones[(df_canciones.artist=="Queen") & (df_canciones.track.str.contains("Remastered"))].track.nunique()

91

<h4>3. ¿Cuantos artistas diferentes hay en los datos? ¿Y canciones diferentes?<h4>

In [25]:
print("Hay", df_canciones.track.nunique(), "canciones y", df_canciones.artist.nunique(), "artistas.")

Hay 39455 canciones y 1485 artistas.

<h4>4. ¿Cuál es la canción con más géneros? ¿Y la que menos?

In [ ]:
#Utilizando map
(
    df_canciones
    .assign(
        n_generos=df_canciones.genres.map(lambda x: len(x))
    )
    .nlargest(1, "n_generos")
)

,track,album,artist,duration,genres,n_generos
15964,Amorphous Surprise,The Bears for Lunch,Guided By Voices,119467,"[alternative country, alternative pop, alterna...",31

In [ ]:
#Utilizando apply
(
    df_canciones
    .assign(
        n_generos=df_canciones.genres.apply(lambda x: len(x))
    )
    .nsmallest(1, "n_generos")
)

         track album artist  duration genres  n_generos
200  All I Ask    25  Adele    271800  [pop]          1

<h4>5. ¿Cuántos segundos de duración suman todas las canciones? <h4>

In [33]:
#Duración estaba en milisegundos, lo pasamos a segundos
df_canciones.duration.sum()/1000

np.float64(10892558.25)

<h4>6. ¿Qué artista ha compuesto más canciones?

In [ ]:
#Canciones únicas + duración total por artista
(
    df_canciones
    .groupby("artist")
    .agg(
        n_canciones=("track", "nunique"),
        duracion_total=("duration", "sum")
    )
    .sort_values("duracion_total", ascending=False)      
)

                             n_canciones  duracion_total
artist
Marillion                            140        50713084
Phish                                135        49316679
Rush                                 154        48363781
Grateful Dead                        142        47699118
Iron Maiden                          135        46091627
...                                  ...             ...
Comedian Bob Marley                    1           36040
Halloween Dance Party                  1           29438
America's Hottest Ringtones            1           29394
I Love Halloween                       1           18065
Halloween AAA                          1           13250

[1485 rows x 2 columns]

In [ ]:
#Otra opción, nº registros por artista
(
    df_canciones
    .groupby("artist")
    .agg(
        n_canciones=("track", "count"),
        
    )
    .sort_values("n_canciones", ascending=False)      
).head(3)

               n_canciones
artist
George Strait          179
Bob Dylan              176
Nazareth               170

In [ ]:
#Cuantos duplicados hay de canciones por artista
df_canciones.duplicated(subset=["artist", "track"]).sum()

np.int64(35)

<h4>7. ¿Qué album contiene más canciones? ¿Y más artistas diferentes?<h4>

In [50]:
 (
    df_canciones
    .groupby("album")
    .agg(
        n_canciones=("track", "nunique"),
    )
    .sort_values("n_canciones", ascending=False)
    .head(3)
    )

                            n_canciones
album
Greatest Hits                       114
Love Songs                           74
The Complete Hank Williams           64

In [51]:
(
    df_canciones
    .groupby("album")
    .agg(
        n_artistas=("artist", "nunique"),
    )
    .sort_values("n_artistas", ascending=False)
    .head(3)
    )

                n_artistas
album
Greatest Hits           44
Love Songs              23
The Collection          13

<h4>8.¿Qué album tiene mayor duración?<h4>

In [53]:
(
    df_canciones
    .groupby("album")
    .agg(
        n_album=("duration", "sum"),
    )
    .sort_values("n_album", ascending=False)
    .head(3)
    )

                 n_album
album
Greatest Hits   26656220
Love Songs      17973542
The Collection  10293920

<h4>9. ¿Qué artista compone, en media, las canciones más largas?¿Y las más cortas?

In [57]:
(
    df_canciones
    .groupby("artist")
    .agg(
        cancion_larga=("duration", "mean"),
    )
    .nlargest(3, "cancion_larga")
    )

                                                   cancion_larga
artist
Blind Faith                                            1156227.0
Deep Purple With The Royal Philharmonic Orchestra      1151067.0
George Gershwin                                         946400.0

In [58]:
(
    df_canciones
    .groupby("artist")
    .agg(
        cancion_larga=("duration", "mean"),
    )
    .nsmallest(3, "cancion_larga")
    )

                             cancion_larga
artist
Halloween AAA                      13250.0
I Love Halloween                   18065.0
America's Hottest Ringtones        29394.0

<h4>10. ¿Qué porcentaje de las canciones son de género rock?<h4 >

In [63]:
(
    df_canciones
    .assign(
        genero_rock=df_canciones.genres.apply(lambda x: "rock" in x)
    )
    .agg(
        {"genero_rock": lambda s: s.sum()/s.count()}
    )
    
)

genero_rock    0.383465
dtype: float64

In [65]:
# option 2
(
    df_canciones
    .assign(
        is_rock=lambda df: df.genres.map(lambda genres: "rock" in genres)
    )
    .agg(
        {"is_rock": lambda s: s.sum() / s.count()}
    )
)

is_rock    0.383465
dtype: float64